services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: seyalicraft/nidhiflow-backend:latest
    container_name: nidhiflow-backend-app
    ports:
      - "${HOST_PORT:-${PORT:-3000}}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-vectordb}
      - DB_PASSWORD=${DB_PASSWORD:-vector_admin}
      - DB_DATABASE=${DB_DATABASE:-nidhiflow}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${DB_USERNAME:-vectordb}:${DB_PASSWORD:-vector_admin}@${DB_HOST:-postgres}:${DB_PORT:-5432}/${DB_DATABASE:-nidhiflow}?schema=public}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CACHE_GLOBAL_ENABLED=${REDIS_CACHE_GLOBAL_ENABLED:-true}
      - CACHE_DISABLED_ROUTES=${CACHE_DISABLED_ROUTES:-/health,/api/v1/auth}
      - JWT_SECRET=${JWT_SECRET:-super_secret_jwt_key_minimum_16_chars}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - SEED_DB=${SEED_DB:-true}
      - ADMIN_SEED_PASSWORD=${ADMIN_SEED_PASSWORD:-Murali@123}
      - USER_SEED_PASSWORD=${USER_SEED_PASSWORD:-Murali@123}
    restart: always
    networks:
      - nidhiflow-network

networks:
  nidhiflow-network:
    driver: bridge
